---
- name: Setup systemd Service for mountpoints
  ansible.builtin.template:
    src: systemd_mount.j2
    dest: /etc/systemd/system/{{ item.dest[1:] | replace('/', '-') }}.mount
    mode: 0644
    owner: root
    group: root
  loop: '{{ mounts }}'
  register: systemd_mount_units
- name: Daemon reload
  ansible.builtin.systemd:
    daemon_reload: yes
  when: systemd_mount_units.changed
- name: Activate systemd mount
  ansible.builtin.systemd:
    name: "{{ item.dest[1:] | replace('/', '-') }}.mount"
    state: started
    enabled: yes
    masked: no
  loop: '{{ mounts }}'
